FROM python:3.10-bullseye

# setup environment variable
ENV DockerHOME=/home/server
ARG BRANCH_NAME
ENV BRANCH_NAME="${BRANCH_NAME}"

# set work directory
RUN mkdir -p $DockerHOME

# where your code lives
WORKDIR $DockerHOME
ADD test/ $DockerHOME/
COPY example_protocol/ $DockerHOME/example_protocol/

RUN apt-get update && apt-get upgrade -y
RUN pip install --upgrade pip
RUN python -m pip install git+https://github.com/bgruey/persistent-connection-server.git@"${BRANCH_NAME}"

CMD python server.py
