FROM python:3.10-bullseye

# setup environment variable
ENV DockerHOME=/home/client

# set work directory
RUN mkdir -p $DockerHOME

# where your code lives
WORKDIR $DockerHOME

RUN apt-get update && apt-get upgrade -y

# copy whole project to your docker home directory.
ADD client/ $DockerHOME/
COPY protocol $DockerHOME/protocol

# install dependencies
RUN pip install --upgrade pip
# run this command to install all dependencies
RUN pip install -r requirements.txt

CMD sleep 5
#CMD python main.py
#CMD python -m pytest -vvx test/