FROM python:3.10-bullseye

# setup environment variable
ENV DockerHOME=/home/server

# set work directory
RUN mkdir -p $DockerHOME

# where your code lives
WORKDIR $DockerHOME
ADD test/ $DockerHOME/

RUN apt-get update && apt-get upgrade -y
RUN pip install --upgrade pip
RUN python -m pip install git+https://github.com/bgruey/persistent-connection-server.git@"${BRANCH_NAME}"

CMD python test/server.py