FROM python:3.10-bullseye

# setup environment variable
ENV DockerHOME=/home/client
ARG BRANCH_NAME
ENV BRANCH_NAME="${BRANCH_NAME}"
# set work directory
RUN mkdir -p $DockerHOME

# where your code lives
WORKDIR $DockerHOME
ADD test/ $DockerHOME/

RUN ls -l && echo "BRANCH NAME IS $BRANCH_NAME"
RUN apt-get update && apt-get upgrade -y
RUN pip install --upgrade pip
RUN python -m pip install git+https://github.com/bgruey/persistent-connection-server.git@"${BRANCH_NAME}"
RUN python -m pip install test/requirements.txt

CMD python -m pytest -vvv test/

