name: Build and Test
on:
  [push]
defaults:
  run:
    shell: bash

jobs:
  test-formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade -r requirements-formatting.txt
      - name: Black formatter
        run: |
          black --check client server protocol example_protocol performance_tests
      - name: run Isort
        run: |
          isort --check client server protocol example_protocol performance_tests

  test-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: run test
        run: |
          source test_env
          export $(cut -d= -f1 test_env)
          docker-compose up --build

  test-installation:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: run test
        run: |
          BRANCH_NAME="$(echo ${GITHUB_REF#refs/heads/})"
          python pip install git+git@github.com:bgruey/persistent-connection-server.git@"${BRANCH_NAME}"
          python -c "import PersistentConnectionServer"
          