name: Build and Test
on:
  [push]
defaults:
  run:
    shell: bash

jobs:
  test-formatting:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.10" ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade -r requirements-formatting.txt
      - name: Black formatter
        run: |
          black --check client messages server
      - name: run Isort
        run: |
          isort --check-only client messages server

  test-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: run test
        run: |
          source test_env
          export $(cut -d= -f1 test_env)
          docker-compose up --build -d
          docker exec "${CLIENT_HOST}" pytest  test/
          docker-compose down